In [1]:
import pandas as pd
import numpy as np

In [2]:
top50 = pd.read_csv('data/top50.csv')
top50.tail()

,Unnamed: 0,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
45,46,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88
46,47,Te Robar�,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88
47,48,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,88
48,49,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88
49,50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82

In [3]:
top50["Genre"].unique()

array(['canadian pop', 'reggaeton flow', 'dance pop', 'pop', 'dfw rap',
       'trap music', 'country rap', 'electropop', 'reggaeton',
       'panamanian pop', 'canadian hip hop', 'latin', 'escape room',
       'pop house', 'australian pop', 'edm', 'atl hip hop', 'big room',
       'boy band', 'r&b en espanol', 'brostep'], dtype=object)

In [4]:
len(top50["Genre"].unique())

21

In [5]:
top50["Genre"].nunique()

21

In [6]:
top50["Genre"].value_counts()

dance pop           8
pop                 7
latin               5
canadian hip hop    3
edm                 3
reggaeton           2
reggaeton flow      2
panamanian pop      2
canadian pop        2
electropop          2
country rap         2
dfw rap             2
brostep             2
trap music          1
escape room         1
pop house           1
australian pop      1
atl hip hop         1
big room            1
boy band            1
r&b en espanol      1
Name: Genre, dtype: int64

In [7]:
def minutes_seconds(seconds):
    minutes = seconds // 60
    seconds = seconds % 60
    return f'{minutes}:{seconds:02d}'

In [8]:
print(minutes_seconds(121))
print(minutes_seconds(3))

2:01
0:03

In [9]:
top50['Length.Pretty'] = top50['Length.'].apply(minutes_seconds)
top50.head()

,Unnamed: 0,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity,Length.Pretty
0,1,Se�orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79,3:11
1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92,5:02
2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85,3:06
3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86,3:18
4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94,2:55

In [10]:
top = top50

In [11]:
top['Energy'].apply(lambda x: round(x/10)).head()

0    6
1    8
2    8
3    6
4    6
Name: Energy, dtype: int64

In [12]:
top['Length.'].apply(lambda seconds: f'{seconds // 60}:{(seconds % 60):02d}')

0     3:11
1     5:02
2     3:06
3     3:18
4     2:55
5     3:40
6     2:11
7     3:22
8     2:37
9     3:14
10    4:11
11    3:05
12    3:02
13    4:48
14    3:25
15    4:21
16    4:03
17    2:38
18    2:41
19    2:53
20    2:33
21    1:55
22    5:09
23    4:26
24    3:15
25    3:11
26    3:30
27    3:33
28    3:13
29    3:42
30    3:30
31    2:59
32    2:56
33    3:20
34    3:44
35    2:44
36    3:46
37    2:42
38    3:01
39    3:19
40    3:48
41    2:51
42    3:36
43    3:18
44    2:42
45    3:02
46    3:22
47    3:34
48    3:38
49    3:26
Name: Length., dtype: object

In [13]:
top.columns

Index(['Unnamed: 0', 'Track.Name', 'Artist.Name', 'Genre', 'Beats.Per.Minute',
       'Energy', 'Danceability', 'Loudness..dB..', 'Liveness', 'Valence.',
       'Length.', 'Acousticness..', 'Speechiness.', 'Popularity',
       'Length.Pretty'],
      dtype='object')

In [14]:
top.index

RangeIndex(start=0, stop=50, step=1)

In [15]:
top.shape

(50, 15)

In [16]:
# top.sort_values('Track.Name')
# top.sort_values('Artist.Name')
top.sort_values('Length.', ascending=False)

,Unnamed: 0,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity,Length.Pretty
22,23,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92,79,81,-4,9,58,309,14,7,83,5:09
1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92,5:02
13,14,Otro Trago - Remix,Sech,panamanian pop,176,79,73,-2,6,76,288,7,20,87,4:48
23,24,Soltera - Remix,Lunay,latin,92,78,80,-4,44,80,266,36,4,91,4:26
15,16,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82,4:21
10,11,Callaita,Bad Bunny,reggaeton,176,62,61,-5,24,24,251,60,31,93,4:11
16,17,LA CANCI�N,J Balvin,latin,176,65,75,-6,11,43,243,15,32,90,4:03
40,41,Higher Love,Kygo,edm,104,68,69,-7,10,40,228,2,3,88,3:48
36,37,Otro Trago,Sech,panamanian pop,176,70,75,-5,11,62,226,14,34,91,3:46
34,35,Never Really Over,Katy Perry,dance pop,100,88,77,-5,32,39,224,19,6,89,3:44
29,30,QUE PRETENDES,J Balvin,latin,93,79,64,-4,36,94,222,3,25,89,3:42
5,6,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102,68,80,-5,9,84,220,9,4,84,3:40
48,49,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88,3:38
42,43,Shallow,Lady Gaga,dance pop,96,39,57,-6,23,32,216,37,3,87,3:36
47,48,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,88,3:34
27,28,It's You,Ali Gatie,canadian hip hop,96,46,73,-7,19,40,213,37,3,89,3:33
26,27,Dance Monkey,Tones and I,australian pop,98,59,82,-6,18,54,210,69,10,83,3:30
30,31,Takeaway,The Chainsmokers,edm,85,51,29,-8,10,36,210,12,4,84,3:30
49,50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82,3:26
14,15,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101,50,83,-4,12,10,205,10,5,92,3:25
7,8,How Do You Sleep?,Sam Smith,pop,111,68,48,-5,8,35,202,15,9,90,3:22
46,47,Te Robar�,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88,3:22
33,34,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98,59,80,-7,13,18,200,2,15,89,3:20
39,40,"fuck, i'm lonely (with Anne-Marie) - from �13 ...",Lauv,dance pop,95,56,81,-6,6,68,199,48,7,78,3:19
43,44,Talk,Khalid,pop,136,40,90,-9,6,35,198,5,13,84,3:18
3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86,3:18
24,25,bad guy (with Justin Bieber),Billie Eilish,electropop,135,45,67,-11,12,68,195,25,30,89,3:15
9,10,bad guy,Billie Eilish,electropop,135,43,70,-11,10,56,194,33,38,95,3:14
28,29,Con Calma,Daddy Yankee,latin,94,86,74,-3,6,66,193,11,6,91,3:13
0,1,Se�orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79,3:11
25,26,If I Can't Have You,Shawn Mendes,canadian pop,124,82,69,-4,13,87,191,49,6,70,3:11
2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85,3:06
11,12,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96,71,82,-4,15,38,185,28,7,86,3:05
45,46,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88,3:02
12,13,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88,3:02
38,39,Sucker,Jonas Brothers,boy band,138,73,84,-5,11,95,181,4,6,80,3:01
31,32,7 rings,Ariana Grande,dance pop,140,32,78,-11,9,33,179,59,33,89,2:59
32,33,0.958333333333333,Maluma,reggaeton,96,71,78,-5,9,68,176,22,28,89,2:56
4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94,2:55
19,20,Truth Hurts,Lizzo,escape room,158,62,72,-3,12,41,173,11,11,91,2:53
41,42,You Need To Calm Down,Taylor Swift,dance pop,85,68,77,-6,7,73,171,1,5,90,2:51
35,36,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114,72,66,-7,14,32,164,18,6,89,2:44
37,38,Antisocial (with Travis Scott),Ed Sheeran,pop,152,82,72,-5,36,91,162,13,5,87,2:42
44,45,Con Altura,ROSAL�A,r&b en espanol,98,69,88,-4,5,75,162,39,12,88,2:42
18,19,Lalala,Y2K,canadian hip hop,130,39,84,-8,14,50,161,18,8,88,2:41
17,18,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90,48,76,-6,7,91,158,56,5,91,2:38
8,9,Old Town Road - Remix,Lil Nas X,country rap,136,62,88,-6,11,64,157,5,10,87,2:37
20,21,Piece Of Your Heart,MEDUZA,pop house,124,74,68,-7,7,63,153,4,3,91,2:33
6,7,Ransom,Lil Tecca,trap music,180,64,75,-6,7,23,131,2,29,92,2:11
21,22,Panini,Lil Nas X,country rap,154,59,70,-6,12,48,115,34,8,91,1:55

In [17]:
top.isnull()

,Unnamed: 0,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity,Length.Pretty
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
top.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        50 non-null     int64
 1   Track.Name        50 non-null     object
 2   Artist.Name       50 non-null     object
 3   Genre             50 non-null     object
 4   Beats.Per.Minute  50 non-null     int64
 5   Energy            50 non-null     int64
 6   Danceability      50 non-null     int64
 7   Loudness..dB..    50 non-null     int64
 8   Liveness          50 non-null     int64
 9   Valence.          50 non-null     int64
 10  Length.           50 non-null     int64
 11  Acousticness..    50 non-null     int64
 12  Speechiness.      50 non-null     int64
 13  Popularity        50 non-null     int64
 14  Length.Pretty     50 non-null     object
dtypes: int64(11), object(4)
memory usage: 6.0+ KB

In [19]:
top.to_csv('data/top50nice.csv', index=False)

In [20]:
top.to_html('data/top50.html')

In [35]:
duomenys_html = pd.read_html('https://lt.wikipedia.org/wiki/Vilniaus_miesto_savivaldyb%C4%97')
type(duomenys_html)

list

In [25]:
for duomuo in duomenys_html:
    print(type(duomuo))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [34]:
duomenys_html[6]

   Savivaldybės istorija                            \
                   Metai Plotas, km² Gyventojų sk.
0                1942 m.         NaN       146 300
1                1949 m.       139.0           NaN
2                1957 m.         NaN           NaN
3                1959 m.       142.0       230 769
4                1967 m.       153.0       316 400
5                1970 m.       265.0       372 100
6                1972 m.       262.0           NaN
7                1976 m.       263.0       445 900
8                1979 m.         NaN       475 825
9                1988 m.       287.0       577 000
10               1989 m.       287.0       576 747
11               1999 m.       401.0       588 400
12    2001 m. (Išsamiau)       401.0       553 904

                                            \
                              Suskirstymas
0                                      NaN
1   5 miesto rajonai (11 miesto apylinkių)
2                         4 miesto rajonai
3                         4 miesto rajonai
4                                      NaN
5                         4 miesto rajonai
6                         4 miesto rajonai
7                                      NaN
8                         4 miesto rajonai
9                         4 miesto rajonai
10                                     NaN
11                                     NaN
12                            21 seniūnija


                                 Gyvenvietės
0                                        NaN
1                                        NaN
2                                        NaN
3                        1 miestas (Vilnius)
4                                        NaN
5                                  1 miestas
6                                  1 miestas
7                                  1 miestas
8                                  1 miestas
9                                  1 miestas
10                                 1 miestas
11                                       NaN
12  2 miestai (Grigiškės, Vilnius), 3 kaimai

In [38]:
istorija = duomenys_html[6]
istorija

   Savivaldybės istorija                            \
                   Metai Plotas, km² Gyventojų sk.
0                1942 m.         NaN       146 300
1                1949 m.       139.0           NaN
2                1957 m.         NaN           NaN
3                1959 m.       142.0       230 769
4                1967 m.       153.0       316 400
5                1970 m.       265.0       372 100
6                1972 m.       262.0           NaN
7                1976 m.       263.0       445 900
8                1979 m.         NaN       475 825
9                1988 m.       287.0       577 000
10               1989 m.       287.0       576 747
11               1999 m.       401.0       588 400
12    2001 m. (Išsamiau)       401.0       553 904

                                            \
                              Suskirstymas
0                                      NaN
1   5 miesto rajonai (11 miesto apylinkių)
2                         4 miesto rajonai
3                         4 miesto rajonai
4                                      NaN
5                         4 miesto rajonai
6                         4 miesto rajonai
7                                      NaN
8                         4 miesto rajonai
9                         4 miesto rajonai
10                                     NaN
11                                     NaN
12                            21 seniūnija


                                 Gyvenvietės
0                                        NaN
1                                        NaN
2                                        NaN
3                        1 miestas (Vilnius)
4                                        NaN
5                                  1 miestas
6                                  1 miestas
7                                  1 miestas
8                                  1 miestas
9                                  1 miestas
10                                 1 miestas
11                                       NaN
12  2 miestai (Grigiškės, Vilnius), 3 kaimai

In [39]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///data/demo_istorija.db')
engine

Engine(sqlite:///data/demo_istorija.db)

In [40]:
istorija.to_sql('istorija', con=engine, index=False)

13

In [42]:
duomenys_sql = pd.read_sql('istorija', con=engine)
duomenys_sql

,"('Savivaldybės istorija', 'Metai')","('Savivaldybės istorija', 'Plotas, km²')","('Savivaldybės istorija', 'Gyventojų sk.')","('Savivaldybės istorija', 'Suskirstymas')","('Savivaldybės istorija', 'Gyvenvietės')"
0,1942 m.,NaN,146 300,None,None
1,1949 m.,139.0,None,5 miesto rajonai (11 miesto apylinkių),None
2,1957 m.,NaN,None,4 miesto rajonai,None
3,1959 m.,142.0,230 769,4 miesto rajonai,1 miestas (Vilnius)
4,1967 m.,153.0,316 400,None,None
5,1970 m.,265.0,372 100,4 miesto rajonai,1 miestas
6,1972 m.,262.0,None,4 miesto rajonai,1 miestas
7,1976 m.,263.0,445 900,None,1 miestas
8,1979 m.,NaN,475 825,4 miesto rajonai,1 miestas
9,1988 m.,287.0,577 000,4 miesto rajonai,1 miestas
10,1989 m.,287.0,576 747,None,1 miestas
11,1999 m.,401.0,588 400,None,None
12,2001 m. (Išsamiau),401.0,553 904,21 seniūnija,"2 miestai (Grigiškės, Vilnius), 3 kaimai"